[tools]
node = "22"

[settings]
experimental = true

[tasks.setup]
run = [
  "git lfs install --local",
  "git lfs pull",
  "mise exec -- npm install",
]

[tasks.deploy]
depends = ["setup"]
run = [
  "./build.js --minify",
  "rsync -a --del --info=progress2 -f'P /hiorbit' build.tmp/ eacs.io:www-eacs/",
]
