[tools]
node = "22"

[settings]
experimental = true

[tasks.setup]
run = [
  "git lfs install --local",
  "git lfs pull",
  "mise install",
  "mise exec -- npm install",
]

[tasks.publish]
run = [
  "mise run setup",
  "mise exec -- npx vite build",
  "rsync -a --del --info=progress2 -f'P /hiorbit' dist.tmp/ eacs.io:www-eacs/",
]
